[main]
log_level = "info"
log_format = "json"
secret_key = "SECRET-KEY-HERE"
data_directory = "data"

[server]
host = "0.0.0.0"
port = 8000
base_url = "/"

[database]
source = "sqlite3:data/db.sqlite3"
