---
- hosts: rasp
  gather_facts: true

  vars:
    unins_pkg:
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
      - containerd
      - runc

    docker_pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  pre_tasks:
    - name: Exit if service manager not systemd
      ansible.builtin.fail:
        msg: "Not a systemd distro, quitting."
      when: ansible_service_mgr != 'systemd'

  tasks:
    - name: Uninstall unoff-pkgs, containerd and runc
      ansible.builtin.apt:
        name: "{{ unins_pkg }}"
        state: absent
        autoremove: true
        purge: true

    - name: Creating directory with perms
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Get GPG keys
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        force: true
        mode: a+r

    - name: Add repo to apt source list
      ansible.builtin.deb822_repository:
        name: "docker-rep"
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_distribution_release }}"
        components: stable
        signed_by: /etc/apt/keyrings/docker.asc

    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 7200

    - name: Install docker packages
      ansible.builtin.apt:
        name: "{{ docker_pkg }}"
        state: present
      notify:
        - Enable and Start Docker

    - name: Flush Handler
      ansible.builtin.meta: flush_handler

    - name: Ensure Docker service is active
      ansible.builtin.systemd_service:
        name: docker.service
      register: dkr_svc_details
      until: dkr_svc_details.status.ActiveState=='active'
      retries: 5
      delay: 5

  handlers:
    - name: Enable and Start Docker
      ansible.builtin.service:
        name: docker.service
        enabled: true
        state: started
