---
- hosts: rasp
  vars:
    config_list:
      - key: PermitEmptyPasswords
        value: "no"
      - key: PermitRootLogin
        value: "no"
      - key: AllowUsers
        value: "{{ lookup('env','USER') }}"
      - key: Port
        value: 2222
      - key: PasswordAuthentication
        value: "yes"
      - key: PubKeyAuthentication
        value: "yes"
      - key: MaxAuthTries
        value: 3
      - key: AllowTcpForwarding
        value: "no"
      - key: AuthorizedKeysFile
        value: /etc/ssh/ansible/authorized_keys

  tasks:
    - name: Backup current ssh config
      copy:
        remote_src: true
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/cfg_backup/sshd_config
        backup: true

    - name: Secure SSH config change
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^(#)?{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
        state: present
        validate: sshd -t -f %s
      loop:
        "{{ config_list }}"
      notify:
        - Restart sshd

    - name: Install UFW on host
      ansible.builtin.apt:
        name: ufw
        state: present
        enabled: true

    - name: Allow SSH Port
      community.general.ufw:
        rule: allow
        port: "{{ config_list | selectattr('name', 'equalto', 'Port') }}"
        proto: tcp

    - name: Flush Handlers
      ansible.builtin.meta: flush_handlers

    - name: Wait for sshd to restart
      ansible.builtin.wait_for:
        connect_timeout: 5
        delay: 5
        host: "{{ ansible_host }}"
        port: "{{ config_list | selectattr('name', 'equalto', 'Port') }}"
        state: started
        timeout: 300

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
