worker_processes auto;

events { worker_connections 1024; }

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 443 ssl;
        server_name pdfding.koji.internal;

        ssl_certificate /etc/nginx/ssl/koji.internal+3.pem;
        ssl_certificate_key /etc/nginx/ssl/koji.internal+3-key.pem;

        location / {
            proxy_pass http://pdfding:8000;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }

    server {
        listen 443 ssl;
        server_name readeck.koji.internal;

        ssl_certificate /etc/nginx/ssl/koji.internal+3.pem;
        ssl_certificate_key /etc/nginx/ssl/koji.internal+3-key.pem;

        location / {
            proxy_pass http://readeck:8000;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }

    server {
        listen 443 ssl;
        server_name joplin-serv.koji.internal;

        ssl_certificate /etc/nginx/ssl/koji.internal+3.pem;
        ssl_certificate_key /etc/nginx/ssl/koji.internal+3-key.pem;

        location / {
            proxy_pass http://joplin-server:8080;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
}
