---
services:
  pdfding:
    image: mrmn/pdfding:latest
    container_name: pdfding
    volumes:
      - sqlite_data:/home/nonroot/pdfding/db
      - media:/home/nonroot/pdfding/media
    env_file:
      - ./env_files/pdfding.env
    networks:
      - rproxy_network


volumes:
  sqlite_data:
  media:


networks:
  rproxy_network:
    external: true
