---
services:
  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    ports:
      - 9005:8000
    volumes:
      - ./readeck-data:/readeck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3
