---
- hosts: rasp
  become: true

  vars:
    files_to_transfer:
      - filename: docker-compose.yaml
        put_at: /opt/readeck/
      - filename: readeck-data/config.toml
        put_at: /opt/readeck/readeck-data

  tasks:
    - name: Create dir for readeck
      ansible.builtin.file:
        path: /opt/readeck/readeck-data
        state: directory

    - name: Transfer files
      ansible.builtin.copy:
        src: "{{ item.filename }}"
        dest: "{{ item.put_at }}"
      loop: "{{ files_to_transfer }}"

    - name: Run command to start readeck
      ansible.builtin.command:
        chdir: /opt/readeck
        cmd: docker compose up -d

    - name: Confirm if container running
      community.docker.docker_container_info:
        name: readeck
      register: readeck_info
      until: readeck_info.exists
      retries: 5
      delay: 5
