---
- hosts: rasp
  gather_facts: yes

  vars:
    network_services:
      - NetworkManager.service
      - systemd-networkd.service

    nm_services:
      - NetworkManager.service
      - NetworkManager-wait-online.service
      - NetworkManager-dispatcher.service
      - network-manager.service

  pre_tasks:
    - name: Exit if service manager not systemd
      ansible.builtin.fail:
        msg: "Not a systemd distro, quitting."
      when: ansible_service_mgr != 'systemd'

  tasks:
    - name: Gather service_facts
      ansible.builtin.service_facts:

    - name: Show default IPv4 config
      ansible.builtin.debug:
        msg: |
          default_ipv4: {{ ansible_default_ipv4 | default('Not Defined') }}

    - name: Extract important variables
      ansible.builtin.set_fact:
        svc: "{{ services }}"
        intf_name: "{{ ansible_default_ipv4.interface }}"
        intf_addr: "{{ ansible_default_ipv4.address }}"
        prefix: "{{ ansible_default_ipv4.prefix }}"
        def_gway: "{{ ansible_default_ipv4.gateway }}"
        dns: "{{ ansible_dns.nameservers }}"

    - name: Status of network managing services, before changes
      ansible.builtin.debug:
        msg: "{{ item }} is {{ svc[item].status }} | default('Service not found!')"
      loop: "{{ network_services }}"
      ignore_errors: true

    - name: Stop, Disable and Mask Network Manager
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        enabled: false
        masked: true
      loop: "{{ nm_services }}"
      when:
        - 'NetworkManager.service' in svc
        - svc['NetworkManager.service'].state == "running" or
          svc['NetworkManager.service'].status == "enabled"

    - name: Creating and copying intf config file for networkd
      ansible.builtin.template:
        src: intf.conf.j2
        dest: /etc/systemd/network/05-{{ intf_name }}.network
      notify:
        - Unmask, Enable and Start networkd

    - name: Flush Handlers
      ansible.builtin.meta: flush_handlers

    - name: Ensure networkd state is running
      ansible.builtin.systemd_service:
        name: systemd-networkd.service
      register: sn_details
      until: sn_details.status.ActiveState=='active'
      retries: 5
      delay: 5

  handlers:
    - name: Unmask, Enable and Start networkd
      ansible.builtin.systemd_service:
        name: systemd-networkd.service
        state: started
        enabled: true
        masked: false
